### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ersin-ertan** [doug-moen/curv#1]
Hello, got stuck at make, after `apt-get install cmake libboost-dev libdouble-conversion-dev libreadline-dev` any ideas?
<details>

```

[ 82%] Building CXX object CMakeFiles/tester.dir/tests/eval.cc.o
/home/mehmet/curv/tests/eval.cc: In function ‘testing::AssertionResult evaltest(const char*, const char*, Expectation)’:
/home/mehmet/curv/tests/eval.cc:162:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors
CMakeFiles/tester.dir/build.make:86: recipe for target 'CMakeFiles/tester.dir/tests/eval.cc.o' failed
make[4]: *** [CMakeFiles/tester.dir/tests/eval.cc.o] Error 1
make[4]: Leaving directory '/home/mehmet/curv/build'
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/tester.dir/all' failed
make[3]: *** [CMakeFiles/tester.dir/all] Error 2
make[3]: Leaving directory '/home/mehmet/curv/build'
CMakeFiles/Makefile2:186: recipe for target 'CMakeFiles/tests.dir/rule' failed
make[2]: *** [CMakeFiles/tests.dir/rule] Error 2
make[2]: Leaving directory '/home/mehmet/curv/build'
Makefile:201: recipe for target 'tests' failed
make[1]: *** [tests] Error 2
make[1]: Leaving directory '/home/mehmet/curv/build'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

```

</details>

**Comment by doug-moen** [comment]
The function evaltest() has a control path where it calls assert(0) to abort the program, and there is no return statement in that control path. In your dev environment, either assert calls are being compiled out (-DNDEBUG is defined), or the compiler is different or different options are being enabled by -Wall.

The code should be fixed to prevent this warning. Maybe throw an exception instead of using `assert(0)`. Maybe this: `throw std::logic_error("can't happen");`

Are you a C++ programmer? If yes, wanna try fixing it and submit a pull request? If no, that's cool, I'll fix it.

**Comment by ersin-ertan** [comment]
Nope no C++, was simply following the instructions in BUILD.md

Hmm, the link points to https://github.com/doug-moen/glslViewer which has the readme's install pointing to `git clone http://github.com/patriciogonzalezvivo/glslViewer`

however, the commit message in curvs BUILD.md says "use my own fork of glslViewer" does that mean to say that the above instruction(your glslViewer's readme) should be changed `git clone http://github.com/doug-moen/glslViewer`?

**Comment by doug-moen** [comment]
The build failure should be fixed now. Try it and see.

**Comment by doug-moen** [comment]
@ersin-ertan: I'm temporarily using a fork of glslViewer while I wait for @patriciogonzalezvivo to accept or comment on my pull request. I am reluctant to make further changes to my fork until I hear from Patricio.

**Comment by patriciogonzalezvivo** [comment]
Hi @doug-moen! Sorry I didn't realize I was blocking you. This is related to https://github.com/patriciogonzalezvivo/glslViewer/issues/70 ?

**Comment by ersin-ertan** [comment]
Was stuck, even though `apt-get install cmake libboost-dev libdouble-conversion-dev libreadline-dev
` installed correctly.
```
[100%] Linking CXX executable curv
/usr/bin/ld: cannot find -lboost_filesystem
/usr/bin/ld: cannot find -lboost_system
```

but quick search turned up `apt-get install libboost-all-dev`
followed by `make` and `make install`

**Comment by doug-moen** [comment]
@ersin-ertan: thanks, I updated the build instructions.
