### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by iplayfast** [doug-moen/curv#10]
If there is no file argument start interpreting stdin as the curve file or alternatively add an option to interpret stdin as the input file. Then you could do stuff like

cat vase.curv | curv 

which might make things easier for adding an ide on top of it. I think that's what openscad did.

**Comment by doug-moen** [comment]
`curv` with no arguments starts up the interactive command line interpreter, which is a valuable feature.

On Linux and macOS, `curv /dev/stdin` does what you have asked for.

I need a man page for the curv command.

IDE integration will have to be worked out on a case-by-case basis. The Language Server Protocol is something we might consider implementing, for integration with certain IDEs. See: https://en.wikipedia.org/wiki/Language_Server_Protocol
