### ISSUE TITLE
Curv for VR /AR

### ISSUE THREAD

**Issue by Automageek** [doug-moen/curv#18]
There is a lot of effort going into medical imaging, search and rescue, architecture, product placement and *lots* of other applications.  With the speed of model rendering in Curv, many prototype iterations could be accomplished and inspected in VR if this feature were available.

Something like a flashlight tool to inspect enclosed spaces would be very useful in this case.

Doug, Curv's creator, has a CT scan of his brain that he hopes to convert to a solid model.  I can see converting a CT scan into a point cloud, and converting that to an STL (simplification). 

An example application:
I had mentioned to my chiropractor the idea of getting a model of a spine in VR and looking at  anomalies to better understand them.

**Comment by doug-moen** [comment]
VR is not currently on my roadmap, and since there is no active discussion, I'm closing this for now.

**Comment by andybak** [comment]
I have some thoughts/questions on this topic. Should I post here or open a new issue?

**Comment by doug-moen** [comment]
It if matches the topic, you can post here.
