### ISSUE TITLE
How do you register to a google groups mailing list without an account

### ISSUE THREAD

**Issue by galex-713** [doug-moen/curv#21]
Or is one (google account) required? Because I guess I had one, or two, a very very long time ago, for posting comments on youtube, or maybe (very less likely) for email, and that was before Google Great Unification of Accounts and Services, and I totally forgot passwords, usernames, etc. and i would like not to start this over again, especially with Google…
Or maybe a Google account is considered alike a github account, like, it’s okay to be required since you only need one of them instead of both? I’d like to know what’s the current idea here…
Thank you in advance!

**Comment by galex-713** [comment]
It worked, but isn’t there a way to do this without your interaction? so people can do this without opening an issue or asking there and waiting having you to notice?

**Comment by doug-moen** [comment]
You can also join the group without my intervention if you have a google
account.

**Comment by galex-713** [comment]
I meant without your intervention if you don’t have a google account

**Comment by doug-moen** [comment]
There is a barrier to posting to the Curv mailing list. You need to "join",
which either requires a Google account, or an invitation from me.

This barrier benefits me, as list administrator, because I don't have to
spend time each day deleting spam.

**Comment by doug-moen** [comment]
question answered, closing an inactive issue.
