### ISSUE TITLE
How to check if a list contains an element?

### ISSUE THREAD

**Issue by p-e-w** [doug-moen/curv#49]
The best I could come up with without using imperative constructs is

```
contains (list, element) =
  count [for (e in list) if (e == element) e] > 0;
```

which is ugly and horribly inefficient. I guess the efficiency problem could be solved using a `while` loop, but the code would be even uglier.

Might it make sense to add a built-in `contains` operator?

**Comment by doug-moen** [comment]
Thanks for the suggestion. It is now implemented.

**Comment by p-e-w** [comment]
Thanks for the quick followup :+1:
