### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by iplayfast** [doug-moen/curv#9]
when using the live editing function, after quitting the editor the shader did not also quit.

export CURV_EDITOR=gvim
 ./curv -e -l  lollipop.curv

**Comment by doug-moen** [comment]
That sounds reasonable. (The -e flag is not well thought out right now.)

With this change, the CURV_EDITOR variable will need to be set to a command that opens a GUI editor window, and remains running in the foreground until the window is closed. Not all editors are suitable. 'gvim' won't work, but 'gvim -f' will work.

**Comment by doug-moen** [comment]
fixed

**Comment by doug-moen** [comment]
and now documented in docs/README.rst
